/*
 * Java domain class for entity "EserviceBuildingDetails" 
 * Created on 2022-11-18 ( Date ISO 2022-11-18 - Time 11:38:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-18 ( 11:38:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.BuildingRiskDetails;
import com.maan.eway.bean.BuildingRiskDetailsId;

import jakarta.transaction.Transactional;
/**
 * <h2>EserviceBuildingDetailsRepository</h2>
 *
 * createdAt : 2022-11-18 - Time 11:38:42
 * <p>
 * Description: "EserviceBuildingDetails" Repository
 */
 
 
 
public interface BuildingRiskDetailsRepository  extends JpaRepository<BuildingRiskDetails,BuildingRiskDetailsId > , JpaSpecificationExecutor<BuildingRiskDetails> {

//     BuildingRiskDetails findByQuoteNo(String quoteNo);

	Long countByQuoteNo(String quoteNo);

	@Transactional
	void deleteByQuoteNo(String quoteNo);

	List<BuildingRiskDetails> findByQuoteNoOrderByRiskIdAsc(String quoteNo);

	Long countByQuoteNoNotAndEndtCountAndOriginalPolicyNo(String quoteNo, BigDecimal bigDecimal,
			String originalPolicyNo);

	@Transactional
	void deleteByQuoteNoNotAndEndtCountAndOriginalPolicyNo(String quoteNo, BigDecimal bigDecimal,
			String originalPolicyNo);

	List<BuildingRiskDetails> findByQuoteNo(String quoteNo);

	BuildingRiskDetails findByQuoteNoAndSectionId(String quoteNo, String string);

	List<BuildingRiskDetails> findByQuoteNoAndSectionIdNotOrderByRiskIdAsc(String quoteno, String string);

	List<BuildingRiskDetails> findByQuoteNoAndStatusNotOrderByRiskIdAsc(String prevQuoteNo, String string);

	BuildingRiskDetails findByQuoteNoAndRiskIdAndSectionId(String quoteNo, int i, String sectionId);

	List<BuildingRiskDetails> findByQuoteNoAndSectionIdOrderByLocationIdAsc(String quoteNo, String sectionId);

	List<BuildingRiskDetails> findByRequestReferenceNoAndSectionId(String string, String sectionId);

	List<BuildingRiskDetails> findByQuoteNoAndSectionIdAndLocationIdOrderByLocationIdAsc(String quoteNo,
			String sectionId, Integer d);

	List<BuildingRiskDetails> findByQuoteNoAndSectionIdAndLocationId(String quoteNo, String sectionId, Integer d);

	List<BuildingRiskDetails> findByRequestReferenceNoAndSectionIdAndLocationId(String string, String sectionId,
			int locationId);

	List<BuildingRiskDetails> findByQuoteNoAndSectionIdAndLocationIdAndRiskIdOrderByLocationIdAsc(String quoteNo,
			String sectionId, Integer d, Integer riskId);


	@Transactional
	void deleteByRequestReferenceNoAndLocationIdAndRiskIdAndSectionIdAndCoverId(String request, Integer Locationid,
			Integer riskid,String sectionid,Integer CoverId);

	List<BuildingRiskDetails> findByQuoteNoAndSectionIdAndLocationIdAndRiskIdAndCoverIdOrderByLocationIdAsc(
			String quoteNo, String sectionId, Integer d, Integer riskId, Integer coverId);

	BuildingRiskDetails findFirstByQuoteNo(String quoteNo);

	List<BuildingRiskDetails> findByQuoteNoAndCoverId(String quoteNo, Integer coverId);

	BuildingRiskDetails findFirstByQuoteNoAndCoverId(String quoteNo, Integer coverId);

	List<BuildingRiskDetails> findByQuoteNoAndCompanyIdAndProductIdAndSectionIdAndCoverId(String quoteNo,
			String companyId, String valueOf, String sectionId, Integer valueOf2);

	BuildingRiskDetails findFirstByRequestReferenceNo(String requestReferenceNo);

	List<BuildingRiskDetails> findByRequestReferenceNoAndCoverId(String requestReferenceNo, Integer coverId);

	BuildingRiskDetails findFirstByRequestReferenceNoAndCoverId(String requestReferenceNo, Integer coverId);

	List<BuildingRiskDetails> findByRequestReferenceNoAndSectionIdAndLocationIdAndCoverId(String string,
			String sectionId, int locationId, Integer coverId);

	long deleteByRequestReferenceNo(String refNo);

	BuildingRiskDetails findByQuoteNoAndCompanyIdAndProductIdAndSectionIdAndCoverIdAndRiskId(String quoteNo,
			String companyId, String valueOf, String sectionId, Integer valueOf2, Integer valueOf3);
}
