/*
 * Java domain class for entity "ProductMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.CompanyProductMaster;
import com.maan.eway.bean.CompanyProductMasterId;
/**
 * <h2>ProductMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:28
 * <p>
 * Description: "ProductMaster" Repository
 */
 
 
 
public interface CompanyProductMasterRepository  extends JpaRepository<CompanyProductMaster,CompanyProductMasterId > , JpaSpecificationExecutor<CompanyProductMaster> {

	List<CompanyProductMaster> findByCompanyIdAndProductIdOrderByAmendIdDesc(String companyId, int parseInt);
	
	List<CompanyProductMaster> findByCompanyIdAndStatus(String companyId, String status);

	CompanyProductMaster findByProductIdAndCompanyIdAndStatus(Integer productId,String companyId,  String status);
	
	 @Query("select coalesce(c.minimumPremium, 0) " +
	           "from CompanyProductMaster c " +
	           "where c.companyId = :companyId " +
	           "  and c.productId = :productId " +
	           "  and c.amendId = (" +
	           "       select max(cp.amendId) " +
	           "       from CompanyProductMaster cp " +
	           "       where cp.companyId = :companyId " +
	           "         and cp.productId = :productId " +
	           "         and cp.effectiveDateStart <= :today " +  // start date today or before
	           "         and cp.effectiveDateEnd   >  :today " +  // end date after today
	           "  )")
	    BigDecimal findMinPremium(@Param("companyId") String companyId,
	                              @Param("productId") Integer productId,
	                              @Param("today") Date today);

	 CompanyProductMaster findTopByProductIdAndCompanyIdAndStatusOrderByAmendIdDesc(Integer productId, String companyId,
			String string);

	
	

}
