/*
 * Java domain class for entity "EserviceBuildingDetails" 
 * Created on 2022-11-18 ( Date ISO 2022-11-18 - Time 11:38:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-18 ( 11:38:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.BuildingRiskDetails;
import com.maan.eway.bean.EserviceBuildingDetails;
import com.maan.eway.bean.EserviceBuildingDetailsId;
/**
 * <h2>EserviceBuildingDetailsRepository</h2>
 *
 * createdAt : 2022-11-18 - Time 11:38:42
 * <p>
 * Description: "EserviceBuildingDetails" Repository
 */
 
 
 
public interface EserviceBuildingDetailsRepository  extends JpaRepository<EserviceBuildingDetails,EserviceBuildingDetailsId > , JpaSpecificationExecutor<EserviceBuildingDetails> {

/*	EserviceBuildingDetails findByRequestReferenceNoAndRiskIdAndCompanyIdAndProductId(String requestReferenceNo,
			Integer vehicleId, String companyId, Integer valueOf);
*/
	List<EserviceBuildingDetails> findByRequestReferenceNoOrderByRiskIdAsc(String requestReferenceNo);
	EserviceBuildingDetails findByRequestReferenceNoAndQuoteNoAndProductIdAndCompanyId(String requestReferenceNo,
			String quoteNo, String productId, String companyId);

//	EserviceBuildingDetails findByRequestReferenceNoAndRiskId(String requestReferenceNo, Integer vehicleId);

	Long countByRequestReferenceNo(String requestReferenceNo);

	List<EserviceBuildingDetails> findByQuoteNoOrderByRiskIdAsc(String quoteNo);

	//EserviceBuildingDetails findByQuoteNo(String quoteNo);

	List<EserviceBuildingDetails> findByRequestReferenceNoAndProductId(String requestReferenceNo, String productId);

//	EserviceBuildingDetails findByRequestReferenceNoAndRiskIdAndCompanyIdAndProductId(String requestReferenceNo,
//			Integer vehicleId, String companyId, String productId);
	
	Integer countByOriginalPolicyNoAndRiskId(String policyNo, int i);
	List<EserviceBuildingDetails> findByOriginalPolicyNoAndRiskId(String policyNo, int i);
	List<EserviceBuildingDetails> findByPolicyNoAndStatus(String policyNo, String string);
	List<EserviceBuildingDetails> findByPolicyNoAndRiskId(String prevPolicyNo, int i);
	List<EserviceBuildingDetails> findByCustomerId(String customerId);
	List<EserviceBuildingDetails> findByRequestReferenceNo(String requestReferenceNo);
	List<EserviceBuildingDetails> findByPolicyNo(String prevPolicyNo);
	
	EserviceBuildingDetails findByRequestReferenceNoAndRiskIdAndSectionId(String requestReferenceNo, int i,
			String sectionId);
	List<EserviceBuildingDetails> findByOriginalPolicyNoAndRiskIdAndSectionId(String policyNo, int i, String string);
	Integer countByOriginalPolicyNoAndRiskIdAndSectionId(String policyNo, int i, String string);
	
	List<EserviceBuildingDetails> findTopByOriginalPolicyNoAndRiskIdOrderBySectionId(String policyNo, int i);
	
	
	List<EserviceBuildingDetails> findByQuoteNoAndStatusNotOrderByRiskIdAsc(String prevQuoteNo, String string);
	
	
	List<EserviceBuildingDetails> findByRequestReferenceNoAndStatusOrderByRiskIdAsc(String requestReferenceNo,
			String string);
	List<EserviceBuildingDetails> findByRequestReferenceNoAndSectionId(String requestReferenceNo, String sectionId);
	
	List<EserviceBuildingDetails> findAllByRequestReferenceNoAndRiskId(String requestReferenceNo, Integer riskId);
	EserviceBuildingDetails findByRequestReferenceNoAndRiskIdAndSectionIdAndLocationId(String requestReferenceNo, int i,
			String sectionId, Integer valueOf);
	List<EserviceBuildingDetails> findByRequestReferenceNoAndSectionIdAndLocationId(String string, String string2,
			int int1);
	List<EserviceBuildingDetails> findByRequestReferenceNoAndLocationId(String requestReferenceNo, Integer data);
	
	List<EserviceBuildingDetails> findByRequestReferenceNoAndLocationIdInAndSectionIdInAndRiskIdInAndCoverIdIn(String requestReferenceNo,List<Integer> Locationids, List<String> sectionId,List<Integer> Riskid,List<Integer> Coverid);
	List<EserviceBuildingDetails> findTopByOriginalPolicyNoOrderBySectionId(String policyNo);
	
	List<EserviceBuildingDetails> findByRequestReferenceNoAndLocationIdInAndSectionIdInAndRiskIdIn(String requestReferenceNo,List<Integer> Locationids, List<String> sectionId,List<Integer> Riskid);
	List<EserviceBuildingDetails> findByOriginalPolicyNo(String policyNo);
	Integer countByOriginalPolicyNo(String policyNo);
	List<EserviceBuildingDetails> findByRequestReferenceNoAndSectionIdAndLocationId(String requestReferenceNo,
			String sectionId, Integer locationId);

	EserviceBuildingDetails findByRequestReferenceNoAndRiskIdAndSectionIdAndLocationIdAndCoverId(
			String requestReferenceNo, Integer riskId, String sectionId, Integer locationId, Integer coverId);
	
	List<EserviceBuildingDetails>findByRequestReferenceNoAndLocationIdAndSectionIdAndRiskId(String requestReferenceNo,Integer location,String sectionid,Integer riskid);
	 List<EserviceBuildingDetails>findByRequestReferenceNoAndLocationIdAndSectionIdAndRiskIdAndCoverIdIn(String requestReferenceNo,
			Integer locId, String secId, Integer vehId, List<Integer> coverIds);
	

	 List<EserviceBuildingDetails> findByRequestReferenceNoAndStatusNotIn(String requestReferenceNo,
				List<String> statusesNot);
	List<EserviceBuildingDetails> findByRequestReferenceNoAndStatusNotOrderByRiskIdAsc(String requestReferenceNo,
			String status);
	List<EserviceBuildingDetails> findByRequestReferenceNoAndCoverId(String reqRefNo, int i);
	EserviceBuildingDetails findFirstByRequestReferenceNoAndCoverId(String reqRefNo, int i);
	
	long deleteByRequestReferenceNo(String refNo);
	
	List<EserviceBuildingDetails> findByRequestReferenceNoAndSectionIdAndLocationIdAndCoverId(String string,
			String sectionId, int int1, int int2);


	List<EserviceBuildingDetails> findAllByRequestReferenceNoAndLocationId(String requestReferenceNo, Integer riskId);
	List<EserviceBuildingDetails> findByOriginalPolicyNoOrderBySectionId(String policyNo);
	List<EserviceBuildingDetails> findByRequestReferenceNoAndCompanyIdAndProductIdAndSectionIdAndCoverId(
			String requestReferenceNo, String companyId2, String productId2, String valueOf, Integer coverId);
}
