/*
 * Java domain class for entity "CustomerDetails" 
 * Created on 2022-09-02 ( Date ISO 2022-09-02 - Time 18:14:52 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-09-02 ( 18:14:52 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.eway.repository;

import java.util.Date;
import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.maan.eway.bean.EserviceMotorDetails;
import com.maan.eway.bean.EserviceMotorDetailsId;

import jakarta.transaction.Transactional;

/**
 * <h2>CustomerDetailsRepository</h2>
 *
 * createdAt : 2022-09-02 - Time 18:14:52
 * <p>
 * Description: "CustomerDetails" Repository
 */

@Transactional
@Repository

public interface EServiceMotorDetailsRepository extends JpaRepository<EserviceMotorDetails, EserviceMotorDetailsId>,
		JpaSpecificationExecutor<EserviceMotorDetails> {

	List<EserviceMotorDetails> findByRequestReferenceNoAndIdNumber(String requestReferenceNo, String idNumber);

	List<EserviceMotorDetails> findByRequestReferenceNoAndIdNumberOrderByRiskIdDesc(String requestReferenceNo,
			String idNumber);

	List<EserviceMotorDetails> findByRequestReferenceNo(String requestReferenceNo);

	List<EserviceMotorDetails> findByRequestReferenceNoAndIdNumberAndRiskId(String requestReferenceNo, String idNumber,
			Integer valueOf);

	EserviceMotorDetails findByRequestReferenceNoAndRiskId(String requestReferenceNo, Integer vehId);

	List<EserviceMotorDetails> findByRequestReferenceNoInOrderByUpdatedDateDesc(List<String> reqRefNos);

	List<EserviceMotorDetails> findByRequestReferenceNoOrderByRiskIdAsc(String requestReferenceNo);

	EserviceMotorDetails findByRequestReferenceNoAndRiskIdOrderByRiskIdAsc(String requestReferenceNo, Integer RiskId);

	EserviceMotorDetails findByRequestReferenceNoAndQuoteNoAndProductIdAndCompanyId(String requestReferenceNo,
			String quoteNo, String productId, String companyId);

	@Transactional
	List<EserviceMotorDetails> findByRequestReferenceNoAndProductId(String requestReferenceNo, String productId);

	List<EserviceMotorDetails> findByPolicyNoAndStatus(String policyNo, String string);

	@Transactional
	Integer countByOriginalPolicyNo(String policyNo);

	@Transactional
	List<EserviceMotorDetails> findByOriginalPolicyNo(String policyNo);

	@Transactional
	List<EserviceMotorDetails> findByQuoteNoOrderByRiskIdAsc(String prevQuoteNo);

	// List<EserviceMotorDetails> findByQuoteNoAndStatusNotInOrderByRiskIdAsc(String
	// prevQuoteNo, String string);

	List<EserviceMotorDetails> findByQuoteNoAndStatusOrderByRiskIdAsc(String prevQuoteNo, String string);

	List<EserviceMotorDetails> findByRequestReferenceNoAndStatusOrderByRiskIdAsc(String requestReferenceNo,
			String string);

	List<EserviceMotorDetails> findByQuoteNoAndStatusNotOrderByRiskIdAsc(String quoteNo, String string);

	List<EserviceMotorDetails> findByCustomerId(String customerId);

	List<EserviceMotorDetails> findByRequestReferenceNoAndStatusNotOrderByRiskIdAsc(String requestReferenceNo,
			String string);

	EserviceMotorDetails findByQuoteNoAndChassisNumber(String quoteNo, String chassisNumber);

	List<EserviceMotorDetails> findByRequestReferenceNoOrderBySectionNameAsc(String requestReferenceNo);

	List<EserviceMotorDetails> findByRequestReferenceNoAndRiskIdInAndStatusNotOrderByRiskIdAsc(
			String requestReferenceNo, List<Integer> vehicleIds, String string);

	EserviceMotorDetails findByRequestReferenceNoAndRiskIdAndLocationId(String requestReferenceNo, Integer vehicleId,
			Integer valueOf);

	EserviceMotorDetails findByPolicyNo(String policyNo);

	@Query(value = "SELECT DISTINCT " + "c.customer_reference_no, " + "c.id_number, " + "c.client_name, "
			+ "c.title_desc, " + "c.middle_name, " + "c.last_name, " + "m.company_id, " + "m.product_id, "
			+ "m.product_name, " + "m.branch_code, " + "m.request_reference_no, " + "m.quote_no, " + "m.customer_id, "
			+ "m.policy_start_date, " + "m.policy_end_date, " + "m.currency, " + "m.saved_from, " + "m.updated_date, "
			+ "CASE " + "    WHEN m.quote_no IS NULL THEN m.overall_premium_lc " + "    ELSE hp.overall_premium_lc "
			+ "END AS overallPremiumLc " + "FROM eservice_customer_details c "
			+ "JOIN eservice_motor_details m ON c.customer_reference_no = m.customer_reference_no "
			+ "LEFT JOIN personal_info p ON p.customer_reference_no = c.customer_reference_no "
			+ "LEFT JOIN home_position_master hp ON hp.customer_id = p.customer_id "
			+ "WHERE m.company_id = :companyId " + "AND m.product_id = :productId " + "AND m.status = 'Y' "
			+ "AND m.updated_date BETWEEN :startDate AND :endDate " + "AND m.application_id = :applicationId "
			+ "AND m.bdm_code = :bdmCode " + "AND m.branch_code = :branchCode " + "AND m.endorsement_type IS NULL "
			+ "AND (m.saved_from <> 'SQ' OR (m.saved_from = 'POL' AND m.quote_no IS NOT NULL)) "
			+ "ORDER BY m.updated_date DESC", nativeQuery = true)
	List<Object[]> findExistingMotorQuotesOLD(@Param("companyId") String companyId,
			@Param("productId") String productId, @Param("startDate") Date startDate, @Param("endDate") Date endDate,
			@Param("applicationId") String applicationId, @Param("bdmCode") String bdmCode,
			@Param("branchCode") String branchCode, Pageable pageable // <-- pass page number & size here
	);

	@Query(value = "SELECT " + "c.customer_reference_no, " + "c.id_number, " + "c.client_name, " + "c.title_desc, "
			+ "c.middle_name, " + "c.last_name, " + "m.company_id, " + "m.product_id, " + "m.product_name, "
			+ "m.branch_code, " + "m.request_reference_no, " + "m.quote_no, " + "m.customer_id, "
			+ "m.policy_start_date, " + "m.policy_end_date, " + "m.currency, " + "m.saved_from, " + "m.updated_date, "
			+ "CASE " + "    WHEN m.quote_no IS NULL THEN SUM(m.overall_premium_lc) "
			+ "    ELSE MAX(hp.overall_premium_lc) " + "END AS overallPremiumLc " + "FROM eservice_customer_details c "
			+ "JOIN eservice_motor_details m ON c.customer_reference_no = m.customer_reference_no "
			+ "LEFT JOIN personal_info p ON p.customer_reference_no = c.customer_reference_no "
			+ "LEFT JOIN home_position_master hp ON hp.customer_id = p.customer_id "
			+ "WHERE m.company_id = :companyId " + "AND m.product_id = :productId " + "AND m.status = 'Y' "
			+ "AND m.updated_date BETWEEN :startDate AND :endDate " + "AND m.application_id = :applicationId "
			+ "AND m.bdm_code = :bdmCode " + "AND m.branch_code = :branchCode " + "AND m.endorsement_type IS NULL "
			+ "AND (m.saved_from <> 'SQ' OR (m.saved_from = 'POL' AND m.quote_no IS NOT NULL)) " + "GROUP BY "
			+ "c.customer_reference_no, " + "c.id_number, " + "c.client_name, " + "c.title_desc, " + "c.middle_name, "
			+ "c.last_name, " + "m.company_id, " + "m.product_id, " + "m.product_name, " + "m.branch_code, "
			+ "m.request_reference_no, " + "m.quote_no, " + "m.customer_id, " + "m.policy_start_date, "
			+ "m.policy_end_date, " + "m.currency, " + "m.saved_from, " + "m.updated_date "
			+ "ORDER BY m.updated_date DESC", nativeQuery = true)
	List<Object[]> findExistingMotorQuotes(@Param("companyId") String companyId, @Param("productId") String productId,
			@Param("startDate") Date startDate, @Param("endDate") Date endDate,
			@Param("applicationId") String applicationId, @Param("bdmCode") String bdmCode,
			@Param("branchCode") String branchCode, Pageable pageable);

	List<EserviceMotorDetails> findByRequestReferenceNoAndStatusNotIn(String requestReferenceNo,
			List<String> statusesNot);

	EserviceMotorDetails findFirstByRequestReferenceNo(String requestReferenceNo);

	long deleteByRequestReferenceNo(String refNo);

	List<EserviceMotorDetails> findByRegistrationNumber(String numberPlate);
	

}