/*
 * Java domain class for entity "DocumentMaster"
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

 /*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.EserviceCustomerDetails;
import com.maan.eway.bean.EserviceCustomerDetailsId;

import jakarta.transaction.Transactional;

@Transactional
public interface EserviceCustomerDetailsRepository  extends JpaRepository<EserviceCustomerDetails,EserviceCustomerDetailsId > , JpaSpecificationExecutor<EserviceCustomerDetails> {

	EserviceCustomerDetails findByCustomerReferenceNo(String requestReferenceNo);

	Page<EserviceCustomerDetails> findByCompanyIdAndProductId(Pageable paging, String comapanyId, Integer valueOf);

	EserviceCustomerDetails findByVrTinNo(String vrTinNo);

	Page<EserviceCustomerDetails> findByCompanyIdAndProductIdAndCreatedBy(Pageable paging, String comapanyId,
			Integer valueOf, String createdBy);

	Page<EserviceCustomerDetails> findByCompanyIdAndProductIdAndCreatedByAndStatus(Pageable paging, String comapanyId,
			Integer valueOf, String createdBy, String string);

	Page<EserviceCustomerDetails> findByCompanyIdAndBrokerBranchCodeAndProductIdAndCreatedBy(Pageable paging,
			String comapanyId, String brokerBranchCode, Integer valueOf, String createdBy);

	Page<EserviceCustomerDetails> findByCompanyIdAndBranchCodeAndProductIdAndCreatedBy(Pageable paging,
			String comapanyId, String branchCode, Integer valueOf, String createdBy);

	Page<EserviceCustomerDetails> findByCompanyIdAndBrokerBranchCodeAndProductIdAndCreatedByAndStatus(Pageable paging,
			String comapanyId, String brokerBranchCode, Integer valueOf, String createdBy, String string);

	Page<EserviceCustomerDetails> findByCompanyIdAndBranchCodeAndProductIdAndCreatedByAndStatus(Pageable paging,
			String comapanyId, String branchCode, Integer valueOf, String createdBy, String string);

	Page<EserviceCustomerDetails> findByCompanyIdAndBrokerBranchCodeAndCreatedBy(Pageable paging, String comapanyId,
			String brokerBranchCode, String createdBy);

	Page<EserviceCustomerDetails> findByCompanyIdAndBranchCodeAndCreatedBy(Pageable paging, String comapanyId,
			String branchCode, String createdBy);

	Page<EserviceCustomerDetails> findByCompanyIdAndBrokerBranchCodeAndCreatedByAndStatus(Pageable paging,
			String comapanyId, String brokerBranchCode, String createdBy, String string);

	Page<EserviceCustomerDetails> findByCompanyIdAndBranchCodeAndCreatedByAndStatus(Pageable paging, String comapanyId,
			String branchCode, String createdBy, String string);

	List<EserviceCustomerDetails> findByCustomerReferenceNoOrderByEntryDateDesc(String customerReferenceNo);

	Page<EserviceCustomerDetails> findByCompanyIdAndBrokerBranchCodeAndStatusAndCreatedByIn(Pageable paging,
			String comapanyId, String brokerBranchCode, String string, List<String> loginIds);

	Page<EserviceCustomerDetails> findByCompanyIdAndBrokerBranchCodeAndCreatedByIn(Pageable paging, String comapanyId,
			String brokerBranchCode, List<String> loginIds);

	int countByCompanyIdAndCreatedByAndMobileCode1AndMobileNo1(String companyId, String createdBy, String mobileCode1,
			String mobileNo1);

	int countByCompanyIdAndCreatedByAndIdTypeAndIdNumber(String companyId, String createdBy, String idType,
			String idNumber);

	List<EserviceCustomerDetails> findByCompanyIdAndIdNumberAndClientStatus(String companyId, String idNumber,
			String string);

	List<EserviceCustomerDetails> findAllByKraPin(String kraPin);

	List<EserviceCustomerDetails> findAllByMobileNo1(String mobileNo1);

	List<EserviceCustomerDetails> findAllByIdNumber(String idNumber);

	List<EserviceCustomerDetails> findByCompanyIdAndLeadSeqNo(String companyId,
			Long leadSeqNo);

	@Query("SELECT e FROM EserviceCustomerDetails e " + "WHERE e.companyId = :companyId "
			+ "AND e.branchCode = :branchCode " + "AND e.policyHolderTypeid = :policyHolderTypeid "
			+ "AND (e.idNumber = :idNumber OR e.email1 = :email1 OR e.mobileNo1 = :mobileNo1)")
	List<EserviceCustomerDetails> findCustomerDetails(@Param("companyId") String companyId,
			@Param("branchCode") String branchCode, @Param("idNumber") String idNumber,
			@Param("policyHolderTypeid") String policyHolderTypeId, @Param("email1") String email1,
			@Param("mobileNo1") String mobileNo1);

	   Optional<EserviceCustomerDetails> findByCustomerReferenceNoAndCompanyId(String customerReferenceNo,
			String companyId);


	   @Query("SELECT e FROM EserviceCustomerDetails e " + "WHERE e.companyId = :companyId "
				+ "AND e.branchCode = :branchCode " + "AND e.policyHolderTypeid = :policyHolderTypeid "
				+ "AND (e.idNumber = :idNumber OR e.email1 = :email1 OR e.mobileNo1 = :mobileNo1) "
				+ "AND e.customerReferenceNo <> :customerReferenceNo")
		List<EserviceCustomerDetails> findUpdatedCustomerDetails(@Param("companyId") String companyId,
				@Param("branchCode") String branchCode, @Param("idNumber") String idNumber,
				@Param("policyHolderTypeid") String policyHolderTypeId, @Param("email1") String email1,
				@Param("mobileNo1") String mobileNo1, @Param("customerReferenceNo") String customerReferenceNo);

	   Optional<EserviceCustomerDetails> findByPolCustCode(String polCustCode);

	List<EserviceCustomerDetails> findFirstByCustomerReferenceNo(String customerRefNo);

    EserviceCustomerDetails findByEmail1AndCompanyId(String email , String companyId);

}
