/*
 * Java domain class for entity "LoginMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.Date;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.LoginMaster;
import com.maan.eway.bean.LoginMasterId;
/**
 * <h2>LoginMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:27
 * <p>
 * Description: "LoginMaster" Repository
 */
 
 
 
public interface LoginMasterRepository  extends JpaRepository<LoginMaster,LoginMasterId > , JpaSpecificationExecutor<LoginMaster> {

	LoginMaster findByLoginId(String loginId);

	LoginMaster findByLoginIdAndPassword(String userId, String epass);

	LoginMaster findByAgencyCodeAndOaCode(String oaCode, Integer oaCode2);

	LoginMaster findByAgencyCode(String object);

	LoginMaster findByCompanyIdAndLoginId(String companyId, String loginId);

	LoginMaster findByLoginIdAndStatus(String loginId, String string);

	LoginMaster findByLoginIdAndEffectiveDateStartLessThanEqual(String loginId, Date date);

	Integer countByCompanyIdAndLoginId(String companyId, String mobileNo);

	List<LoginMaster> findByOaCode(Integer oaCode);

	List<LoginMaster> findByOaCodeAndCompanyId(Integer oaCode, String comapanyId);

	LoginMaster findByAgencyCodeAndCompanyId(String string, String comapanyId);

	LoginMaster findByAgencyCodeAndOaCodeAndCompanyId(String oaCode, Integer valueOf, String insuranceId);

	List<LoginMaster> findByCompanyIdAndUserType(String companyId, String userType);

	List<LoginMaster> findByCompanyIdAndUserTypeAndSubUserType(String companyId, String userType, String string);

	List<LoginMaster> findByCompanyIdAndLoginIdAndAgencyCode(String companyId, String loginId,String agentcode);

	LoginMaster findByLoginIdAndCompanyId(String loginId, String companyId);
	
	Optional<LoginMaster> findByCompanyIdAndAgencyCode(String companyId, String agencyCode);

	boolean existsByCompanyIdAndAgencyCode(String companyId, String agencyCode);
	

}
