/*
 * Java domain class for entity "MotorDataDetails" 
 * Created on 2022-11-09 ( Date ISO 2022-11-09 - Time 18:32:21 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-09 ( 18:32:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.EserviceMotorDetails;
import com.maan.eway.bean.MotorDataDetails;
import com.maan.eway.bean.MotorDataDetailsId;

import jakarta.transaction.Transactional;
/**
 * <h2>MotorDataDetailsRepository</h2>
 *
 * createdAt : 2022-11-09 - Time 18:32:21
 * <p>
 * Description: "MotorDataDetails" Repository
 */
 
 


public interface MotorDataDetailsRepository  extends JpaRepository<MotorDataDetails,MotorDataDetailsId > , JpaSpecificationExecutor<MotorDataDetails> {

	List<MotorDataDetails> findByQuoteNoOrderByVehicleIdAsc(String quoteNo);

	Long countByQuoteNo(String quoteNo);

	@Transactional
	void deleteByQuoteNo(String quoteNo);

	MotorDataDetails findByQuoteNoAndVehicleId(String quoteNo, String vehicleId);

	Long countByQuoteNoAndVehicleId(String quoteNo, String vehicleId);

	@Modifying
	@Transactional
	@Query("DELETE FROM MotorDataDetails m WHERE m.quoteNo = :quoteNo AND m.vehicleId = :vehicleId")
	void deleteByQuoteNoAndVehicleId(@Param("quoteNo") String quoteNo, @Param("vehicleId") String vehicleId);
	
	List<MotorDataDetails> findByQuoteNo(String quoteNo);

	List<MotorDataDetails> findByQuoteNoAndStatusNotOrderByVehicleIdAsc(String quoteNo, String string);

	List<MotorDataDetails> findByRequestReferenceNoAndStatusNotOrderByVehicleIdAsc(String requestReferenceNo,
			String string);

	List<MotorDataDetails> findByRequestReferenceNoOrderByVehicleIdAsc(String requestReferenceNo);

	List<EserviceMotorDetails> findByRequestReferenceNoOrderBySectionNameAsc(String requestReferenceNo);

	Long countByQuoteNoNotAndEndtCountAndOriginalPolicyNo(String quoteNo, BigDecimal bigDecimal,
			String originalPolicyNo);

	@Transactional
	void deleteByQuoteNoNotAndEndtCountAndOriginalPolicyNo(String quoteNo, BigDecimal bigDecimal,
			String originalPolicyNo);

	@Query(value = "SELECT NUM_TO_WORDS_CONVERT(?1) FROM DUAL",nativeQuery = true)
	String getAmountByWords(Double amtInWordValue);

	List<MotorDataDetails> findByRegistrationNumber(String registrationNumber);
	
	List<MotorDataDetails> findByRegistrationNumberOrderByEntryDateDesc(String chassisno);

	Optional<MotorDataDetails> findFirstByQuoteNo(String quoteNo);

	long deleteByRequestReferenceNo(String refNo);

	MotorDataDetails findTopByQuoteNoOrderByEntryDateDesc(String quoteNo);
	
	@Query("SELECT m.registrationNumber FROM MotorDataDetails m " +
	       "WHERE m.requestReferenceNo = :quoteNo " +
	       "AND m.registrationNumber IS NOT NULL " +
	       "AND m.registrationNumber != '' ")
	List<String> findRegistrationNumberByQuoteNo(@Param("quoteNo") String quoteNo);

	@Query("SELECT m FROM MotorDataDetails m " +
	       "WHERE m.companyId = :companyId " +
	       "AND m.registrationNumber = :registrationNumber " +
	       "AND m.policyNo IS NOT NULL AND m.policyNo != '' " +
	       "AND m.policyEndDate IS NOT NULL " +
	       "AND m.endtPrevPolicyNo IS NULL " +
	       "ORDER BY m.policyEndDate DESC")
	List<MotorDataDetails> findExistingPolicyByRegistrationNumber(
	    @Param("companyId") String companyId,
	    @Param("registrationNumber") String registrationNumber
	);
	
	List<MotorDataDetails> findByRegistrationNumberAndStatus(String regNo, String string);

	List<MotorDataDetails> findByRegistrationNumberAndCompanyIdAndStatus(String regNo, String companyId,String string);
}
