/*
 * Java domain class for entity "OmPaymentDetail" 
 * Created on 2023-01-03 ( Date ISO 2023-01-03 - Time 15:28:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-03 ( 15:28:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jdbc.repository.query.Modifying;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;

import com.maan.eway.bean.PaymentDetail;
import com.maan.eway.bean.PaymentDetailId;
/**
 * <h2>OmPaymentDetailRepository</h2>
 *
 * createdAt : 2023-01-03 - Time 15:28:40
 * <p>
 * Description: "OmPaymentDetail" Repository
 */
 
 
 
public interface PaymentDetailRepository  extends JpaRepository<PaymentDetail,PaymentDetailId > , JpaSpecificationExecutor<PaymentDetail> {



	PaymentDetail findByQuoteNoAndPaymentIdAndMerchantReference(String quoteNo, String paymentId,
			String paymentReferenceNo);

	List<PaymentDetail> findByQuoteNo(String quoteNo);

	List<PaymentDetail> findByQuoteNoOrderByEntryDateDesc(String quoteNo);

	List<PaymentDetail> findByQuoteNoAndPaymentStatusOrderByEntryDateDesc(String quoteNo, String string);

	PaymentDetail findByMerchantReference(String merchantRefernceNo);

	PaymentDetail findByMerchantReferenceAndPaymentTypeAndPaymentStatus(String merchantRefernceNo, String paymentType,String PaymentStatus);

	PaymentDetail findByPaymentId(String paymentId);

	@Query(value="SELECT ITEM_VALUE FROM EWAY_LIST_ITEM_VALUE WHERE ITEM_CODE='CREDIT_URL' AND COMPANY_ID='100004'",nativeQuery=true)
	String getCreditLimitApiURL();

	PaymentDetail findByMerchantReferenceAndPaymentStatus(String merchantRefernceNo, String string);

	List<PaymentDetail> findByQuoteNoOrderByMerchantReferenceAsc(String quoteNo);
	
	@Modifying
    @Transactional
    @Query("UPDATE PaymentDetail p SET p.reference = :reference WHERE p.merchantReference = :merchantReference")
    int updatePaymentDetail(@Param("reference") String reference, @Param("merchantReference") String merchantReference);
	
	
	List<PaymentDetail> findByCompanyIdAndBranchCodeAndPaymentStatus(String companyId, String branchCode, String status);

	List<PaymentDetail> findByQuoteNoAndPaymentId(String orderId, String paymentIds);

	List<PaymentDetail> findByInstalmentReferenceNumber(String instalmentRef);

	Optional<List<PaymentDetail>> findLatestByQuoteNoAndPaymentId(String quoteNo, String paymentId);
	
	PaymentDetail findTopByQuoteNoOrderByEntryDateDesc(String quoteNo);

	PaymentDetail findTopByQuoteNoAndPaymentsOrderByEntryDateDesc(String quoteNo, String string);

	PaymentDetail findByQuoteNoAndPayments(String quoteNo, String string);

	PaymentDetail findByQuoteNoAndPaymentIdAndMerchantReferenceAndPaymentStatusAndPaymentType(String quoteNo,
			String paymentId, String merchRefNo, String string, String paymentType);




	
}
