/*
 * Java domain class for entity "CoverDetails" 
 * Created on 2022-11-09 ( Date ISO 2022-11-09 - Time 18:32:05 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-09 ( 18:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.PolicyCoverData;
import com.maan.eway.bean.PolicyCoverDataId;
/**
 * <h2>CoverDetailsRepository</h2>
 *
 * createdAt : 2022-11-09 - Time 18:32:05
 * <p>
 * Description: "CoverDetails" Repository
 */
 
 

public interface PolicyCoverDataRepository  extends JpaRepository<PolicyCoverData,PolicyCoverDataId > , JpaSpecificationExecutor<PolicyCoverData> {

	List<PolicyCoverData> findByQuoteNo(String quoteNo);
	
	List<PolicyCoverData> findByQuoteNoAndCoverageType(String quoteNo,String coverageType);

	List<PolicyCoverData> findByQuoteNoAndVehicleIdOrderByCoverIdAsc(String quoteNo, Integer i);

	List<PolicyCoverData> findByQuoteNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdOrderByCoverIdAsc(
			String endtPrevQuoteNo, Integer vehicleId, String insuranceId, Integer productId, Integer sectionId);

	List<PolicyCoverData> findByQuoteNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdAndStatusOrderByCoverIdAsc(
			String endtPrevQuoteNo, int parseInt, String insuranceId, int parseInt2, int parseInt3, String string);

	List<PolicyCoverData> findByQuoteNoAndStatusAndCoverageTypeIn(String endtPrevQuoteNo, String string, List<String> coverageTypes);

	List<PolicyCoverData> findByRequestReferenceNo(String referenceNo);

	List<PolicyCoverData> findByQuoteNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdAndStatusAndCoverIdOrderByCoverIdAsc(
			String endtPrevQuoteNo, int parseInt, String insuranceId, int parseInt2, int parseInt3, String string,
			int parseInt4);

	List<PolicyCoverData> findByRequestReferenceNoAndQuoteNo(String referenceNo, String quoteNo);
	
	List<PolicyCoverData> findByQuoteNoAndStatusInAndCoverageTypeIn(String endtPrevQuoteNo, List<String> string, List<String> coverageTypes);

	List<PolicyCoverData> findByPolicyNoAndSectionIdAndCoverIdAndVehicleIdAndCompanyIdOrderByCoverIdAsc(String policyNo, Integer valueOf,
			Integer valueOf2, Integer valueOf3,String insuranceId);

//	List<PolicyCoverData> cc(String quoteNo, String string, Integer string2);

	List<PolicyCoverData> findByQuoteNoAndCoverageTypeAndVehicleId(String quoteNo, String string, Integer i);

	List<PolicyCoverData> findByRequestReferenceNoAndCoverageTypeAndVehicleId(String requestReferenceNo, String coverageType,
			Integer vehicleId);

	List<PolicyCoverData> findByQuoteNoAndVehicleId(String quoteNo, Integer i);

	long deleteByRequestReferenceNo(String refNo);

	List<PolicyCoverData> findByQuoteNoAndVehicleIdAndCompanyIdAndProductIdAndStatusOrderByCoverIdAsc(
			String endtPrevQuoteNo, int int1, String insuranceId, int int2, String string);

	List<PolicyCoverData> findByQuoteNoAndCompanyIdAndProductIdAndStatusOrderByCoverIdAsc(String endtPrevQuoteNo,
			String insuranceId, int int1, String string);
	
	
	
	@Query("SELECT DISTINCT p.locationId, p.sectionId, p.coverId " +
		       "FROM PolicyCoverData p " +
		       "WHERE p.quoteNo = :quoteNo " +
		       "AND p.companyId = :companyId " +
		       "AND p.productId = :productId " +
		       "AND p.requestReferenceNo = :requestReferenceNo " +
		       "AND p.vehicleId <> 99999 " +
		       "AND p.sectionId <> 99999")
		List<Object[]> findDistinctLocationSectionCover(
		        @Param("quoteNo") String quoteNo,
		        @Param("companyId") String companyId,
		        @Param("productId") String productId,
		        @Param("requestReferenceNo") String requestReferenceNo);

	List<PolicyCoverData> findByQuoteNoAndCompanyIdAndProductIdAndSectionIdAndStatusOrderByCoverIdAsc(
			String endtPrevQuoteNo, String insuranceId, int int1, int int2, String string);

	List<PolicyCoverData> findByQuoteNoAndCompanyIdAndProductIdAndSectionIdAndCoverIdAndStatusAndCoverageTypeAndLocationIdOrderByCoverIdAsc(
			String endtPrevQuoteNo, String insuranceId, int int1, int int2, int int3, String string, String string2,
			int int4);

	List<PolicyCoverData> findByQuoteNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdAndStatusAndCoverIdAndLocationIdOrderByCoverIdAsc(
			String endtPrevQuoteNo, int int1, String insuranceId, int int2, int int3, String string, int int4,
			int int5);

	List<PolicyCoverData> findByPolicyNoInAndCoverageTypeNot(List<String> policyNos, String type);
	List<PolicyCoverData> findByQuoteNoInAndCoverageTypeNot(List<String> quoteNos, String type);

	List<PolicyCoverData> findByQuoteNoAndSectionIdAndLocationId(String quoteNo, Integer sectionId, Integer locationId);

	List<PolicyCoverData> findByRequestReferenceNoAndLocationIdAndProductIdAndCompanyIdAndSectionIdAndCoverageType(
		    String requestReferenceNo, Integer locationId, Integer productId,
		    String companyId, Integer sectionId, String coverrageType);

		List<PolicyCoverData> findByQuoteNoOrderByVehicleIdAsc(String quoteNo);




}
