/*
 * Java domain class for entity "SectionMaster" 
 * Created on 2022-09-02 ( Date ISO 2022-09-02 - Time 18:14:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-02 ( 18:14:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.ProductSectionMaster;
import com.maan.eway.bean.ProductSectionMasterId;
/**
 * <h2>SectionMasterRepository</h2>
 *
 * createdAt : 2022-09-02 - Time 18:14:54
 * <p>
 * Description: "SectionMaster" Repository
 */
 
 
 
public interface ProductSectionMasterRepository  extends JpaRepository<ProductSectionMaster,ProductSectionMasterId > , JpaSpecificationExecutor<ProductSectionMaster> {

	List<ProductSectionMaster> findByProductIdAndCompanyId(Integer productId, String companyId);

	Long countBySectionNameAndCompanyIdAndProductIdOrderByEntryDateDesc(String sectionName, String companyId,
			Integer productId);

	List<ProductSectionMaster> findByProductIdAndCompanyIdAndSectionIdAndStatusOrderByAmendIdDesc(Integer productId,
			String companyId, Integer sectionId, String string);

	List<ProductSectionMaster> findByProductIdAndSectionIdAndCompanyIdOrderByAmendIdDesc(Integer valueOf,
			Integer valueOf2, String companyId);

	List<ProductSectionMaster> findBySectionName(String sectionName);
	

	List<ProductSectionMaster> findBySectionNameAndCompanyIdOrderByAmendIdDesc(String sectionName, String companyId);
	
	
	@Query(value = """
		    SELECT * FROM product_section_master p 
		    WHERE p.company_id = :companyId 
		      AND p.product_id = :productId 
		      AND p.section_id = :sectionId 
		      AND p.effective_date_start <= :today 
		      AND p.effective_date_end >= :today 
		      AND p.amend_id = (
		          SELECT MAX(p2.amend_id) 
		          FROM product_section_master p2 
		          WHERE p2.company_id = p.company_id 
		            AND p2.product_id = p.product_id 
		            AND p2.section_id = p.section_id 
		            AND p2.effective_date_start <= :today 
		            AND p2.effective_date_end >= :today
		      )
		    """, nativeQuery = true)
		Optional<ProductSectionMaster> findByCompanyIdAndProductIdAndSectionIdAndDateRangeWithMaxAmendId(
		    @Param("companyId") String companyId,
		    @Param("productId") Integer productId,
		    @Param("sectionId") Integer sectionId,
		    @Param("today") LocalDate today
		);
	
	@Query("SELECT p FROM ProductSectionMaster p " +
		       "WHERE p.sectionId = :sectionId " +
		       "AND p.productId = :productId " +
		       "AND p.companyId = :companyId " +
		       "ORDER BY p.amendId DESC")
		List<ProductSectionMaster> findAllSectionFiles(
		        @Param("sectionId") Integer sectionId,
		        @Param("productId") Integer productId,
		        @Param("companyId") String companyId);

	List<ProductSectionMaster> findByProductIdAndCompanyIdOrderByAmendIdDesc(Integer productId, String companyId);

	List<ProductSectionMaster> findByCompanyIdAndProductIdAndSectionIdOrderByAmendIdDesc(String companyId,
			Integer productId, Integer sectionId);

	List<ProductSectionMaster> findByCompanyIdAndProductIdAndSectionIdAndStatusOrderByAmendIdDesc(String string, Integer productId,
			Integer sectionId, String string2);



//	List<ProductSectionMaster> findByProductIdAndCompanyIdAndEffectiveDateStartGreaterThanEqualAndEffectiveDateEndLessThanEqualMaxAmendId(
//	        String productId,
//	        String companyId,
//	        Date startDate,
//	        Date endDate
//	);

//	@Query("SELECT p FROM ProductSectionMaster p " +
//		       "WHERE p.productId = :productId " +
//		       "AND p.companyId = :companyId " +
//		       "AND p.amendId = (" +
//		       "   SELECT MAX(p2.amendId) FROM ProductSectionMaster p2 " +
//		       "   WHERE p2.productId = :productId AND p2.companyId = :companyId" +
//		       ")")
//		List<ProductSectionMaster> findMaxAmendId(
//		        @Param("productId") Integer productId,
//		        @Param("companyId") String companyId
//		);



	
	

}
