/*
 * Java domain class for entity "BankMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.eway.bean.SectionDataDetails;
import com.maan.eway.bean.SectionDataDetailsId;

import jakarta.transaction.Transactional;

 
 
public interface SectionDataDetailsRepository  extends JpaRepository<SectionDataDetails,SectionDataDetailsId > , JpaSpecificationExecutor<SectionDataDetails> {

	Long countByQuoteNo(String quoteNo);

	@Transactional
	void deleteByQuoteNo(String quoteNo);

	List<SectionDataDetails> findByRequestReferenceNoOrderByRiskIdAsc(String requestReferenceNo);

	List<SectionDataDetails> findBySectionId(String sectionId);

	List<SectionDataDetails> findByQuoteNoOrderByRiskIdAsc(String quoteNo);

	List<SectionDataDetails> findByQuoteNo(String quoteNo);

	List<SectionDataDetails> findByQuoteNoAndStatusOrderByRiskIdAsc(String prevQuoteNo, String string);

	

	List<SectionDataDetails> findByQuoteNoAndStatusNot(String quoteNo, String string);

	Long countByQuoteNoNotAndEndtCountAndOriginalPolicyNo(String quoteNo, BigDecimal bigDecimal,
			String originalPolicyNo);

	@Transactional
	void deleteByQuoteNoNotAndEndtCountAndOriginalPolicyNo(String quoteNo, BigDecimal bigDecimal,
			String originalPolicyNo);
	
	SectionDataDetails findByQuoteNoAndSectionIdAndRiskId(String quoteNo,String sectionId, Integer Riskid);

	List<SectionDataDetails> findByQuoteNoAndStatusNotOrderByRiskIdAsc(String prevQuoteNo, String string);

	List<SectionDataDetails> findByRequestReferenceNoAndStatusNotOrderByRiskIdAsc(String previousRequestReferenceNo,
			String string);

	List<SectionDataDetails> findByRequestReferenceNoOrderByLocationIdAsc(String requestReferenceNo);

	List<SectionDataDetails> findByRequestReferenceNoAndSectionIdOrderByLocationIdAsc(String prevPolicyNo,
			String sectionId);


	List<SectionDataDetails> findByPolicyNoAndStatusNotAndLocationIdOrderByLocationIdAsc(String prevPolicyNo,
			String string, Integer locationId);

	List<SectionDataDetails> findByPolicyNoAndStatusNotOrderByLocationIdAsc(String prevPolicyNo, String string);

	List<SectionDataDetails> findByPolicyNoAndSectionIdAndLocationIdOrderByLocationIdAsc(String prevPolicyNo,
			String sectionId, Integer locationId);
	SectionDataDetails findByQuoteNoAndLocationIdAndSectionIdAndCoverIdAndRiskId(String quoteNo, Integer locId, String secId, Integer coverId, Integer riskId);
	
	List<SectionDataDetails> findByPolicyNoAndLocationId(String prevPolicyNo,Integer locationId);

	@Query("select s.stickerNumber from SectionDataDetails s where s.quoteNo = :quoteNo")
	String findStickerNumberByQuoteNo(String quoteNo);

	long deleteByRequestReferenceNo(String refNo);

	List<SectionDataDetails> findByOriginalPolicyNoAndStatusNotOrderByLocationIdAsc(String prevPolicyNo, String string);




}
