/*
 * Java domain class for entity "SectionCoverMaster" 
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:44 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-30 ( 18:45:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.SectionCoverMaster;
import com.maan.eway.bean.SectionCoverMasterId;
/**
 * <h2>SectionCoverMasterRepository</h2>
 *
 * createdAt : 2022-09-30 - Time 18:45:44
 * <p>
 * Description: "SectionCoverMaster" Repository
 */
 
 
 
public interface SectionCoverMasterRepository  extends JpaRepository<SectionCoverMaster,SectionCoverMasterId > , JpaSpecificationExecutor<SectionCoverMaster> {

	List<SectionCoverMaster> findByCompanyIdAndSectionIdAndCoverIdOrderByAmendIdDesc(String companyId,
			Integer sectionId, Integer coverId);
	
	List<SectionCoverMaster> findByCompanyIdAndProductIdAndSectionIdAndCoverIdOrderByAmendIdDesc(String companyId,Integer pp,
			Integer sectionId, Integer coverId);
	
	List<SectionCoverMaster> findByCompanyIdAndProductIdAndSectionIdAndCoverIdInOrderByAmendIdDesc(String companyId,Integer pp,
			Integer sectionId, List<Integer> coverId);
	
	
	List<SectionCoverMaster> findByCompanyIdAndProductIdAndSectionIdAndStatusOrderByAmendIdDesc(String companyId,Integer pp,Integer sectionId,String sts);
	
	List<SectionCoverMaster> findByCompanyIdAndProductId(String companyId,Integer productId);
	
	@Query("SELECT COUNT(s) FROM SectionCoverMaster s " +
		       "WHERE s.companyId        = :companyId " +
		       "AND   s.productId        = :productId " +
		       "AND   s.coverId          IN :coverIds " +
		       "AND   s.additionalInfoYN = 'Y' " +
		       "AND   s.status           = 'Y' " +
		       "AND   s.amendId = (" +
		       "       SELECT MAX(s2.amendId) " +
		       "       FROM   SectionCoverMaster s2 " +
		       "       WHERE  s2.companyId  = s.companyId " +
		       "       AND    s2.productId  = s.productId " +
		       "       AND    s2.sectionId  = s.sectionId " +
		       "       AND    s2.coverId    = s.coverId)")
		long countCoversWithAdditionalInfo(
		        @Param("companyId") String        companyId,
		        @Param("productId") Integer       productId,   
		        @Param("coverIds")  List<Integer> coverIds);   

}
