/*
 * Java domain class for entity "BankMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.TermsAndCondition;
import com.maan.eway.bean.TermsAndConditionId;
/**
 * <h2>BankMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:26
 * <p>
 * Description: "BankMaster" Repository
 */
 
 

 
public interface TermsAndConditionRepository  extends JpaRepository<TermsAndCondition,TermsAndConditionId > , JpaSpecificationExecutor<TermsAndCondition> {




	List<TermsAndCondition> findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndRiskIdAndQuoteNoAndId(
			String companyId, String branchCode, String productId, String sectionId, String riskId, String quoteNo,
			Integer valueOf);


	TermsAndCondition findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndRiskIdAndQuoteNoAndIdAndSubId(
			String companyId, String branchCode, String productId, String sectionId, String riskId, String quoteNo,
			Integer valueOf, Integer valueOf2);


	List<TermsAndCondition> findByQuoteNoAndRiskIdAndProductIdAndSectionId(String quoteNo, String riskId,
			String productId, String sectionId);



	List<TermsAndCondition> findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndQuoteNoOrderBySnoAsc(
			String companyId, String branchCode, String productId, String sectionId, String quoteNo);


	List<TermsAndCondition> findByRequestReferenceNoAndRiskIdAndProductIdAndSectionId(String requestReferenceNo,
			String riskId, String productId, String sectionId);


	List<TermsAndCondition> findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndRiskIdAndRequestReferenceNoAndId(
			String companyId, String branchCode, String productId, String sectionId, String riskId,
			String requestReferenceNo, Integer valueOf);


	TermsAndCondition findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndRiskIdAndRequestReferenceNoAndIdAndSubId(
			String companyId, String branchCode, String productId, String sectionId, String riskId,
			String requestReferenceNo, Integer valueOf, Integer valueOf2);


	List<TermsAndCondition> findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndRequestReferenceNoOrderBySnoAsc(
			String companyId, String branchCode, String productId, String sectionId, String requestReferenceNo);


	List<TermsAndCondition> findByRequestReferenceNoAndRiskIdAndProductIdAndSectionIdAndId(String requestReferenceNo,
			String riskId, String productId, String sectionId, Integer id);


	List<TermsAndCondition> findByQuoteNo(String requestReferenceNo);


	List<TermsAndCondition> findByRequestReferenceNo(String requestReferenceNo);
	 
   
    List<TermsAndCondition> findByRequestReferenceNoAndLocationIdAndSectionIdAndCoverIdAndTypeId(
            String requestReferenceNo, String locationId,
            String sectionId, String coverId, String typeId);


	List<TermsAndCondition> findByRequestReferenceNoAndLocationIdAndSectionIdAndCoverId(String requestReferenceNo,
			String locationId, String sectionId, String coverId);

	
	@Modifying
	@Query("DELETE FROM TermsAndCondition t " +
	       "WHERE t.requestReferenceNo = :requestReferenceNo " +
	       "AND   t.quoteNo            = :quoteNo " +
	       "AND   t.coverId NOT IN :validCoverIds " +
	       "AND   t.coverId <> '99999'")
	void deleteByRequestReferenceNoAndQuoteNoAndCoverIdNotIn(
	        @Param("requestReferenceNo") String requestReferenceNo,
	        @Param("quoteNo")            String quoteNo,
	        @Param("validCoverIds")      List<String> validCoverIds);
	


	List<TermsAndCondition> findByRequestReferenceNoAndLocationIdAndSectionIdAndCoverIdAndId(String requestReferenceNo,
			String locationId, String sectionId, String coverId, Integer typeId);


	List<TermsAndCondition> findByRequestReferenceNoAndTypeId(String requestRefNo, String string);


	List<TermsAndCondition> findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndLocationIdAndRequestReferenceNoOrderBySnoAsc(String companyId, String branchCode, String productId, String sectionId, String locationId, String refNO);


	List<TermsAndCondition> findByQuoteNoAndSectionIdInAndCoverIdInAndId(String quoteNo, List<String> sect,
			List<String> cover, Integer i);


	List<TermsAndCondition> findByQuoteNoAndSectionIdInAndId(String quoteNo, Set<String> sectionIds, int i);


	List<TermsAndCondition> findByQuoteNoAndSectionIdInAndCoverIdInAndIdAndLocationId(String quoteNo, List<String> sect,
			List<String> cover, int i, String string);


}
