
#Eway API's
customer.save.api=http://192.168.1.42:8086/api/savecustomerdetails
login.token.api=http://192.168.1.42:8086/authentication/login
nonMotor.save.api=http://192.168.1.42:8085/api/slide/nonmotorsave
calculator.api=http://192.168.1.42:8086/calculator/calc/call
view.calc.api=http://192.168.1.42:8086/api/view/calc
update.factor.rate.api=http://192.168.1.42:8086/api/updatefactorrate
buypolicy.api=http://192.168.1.42:8086/quote/buypolicy
make.payment.api=http://192.168.1.42:8086/payment/makepayment
insert.payment.api=http://192.168.1.42:8086/payment/insertpaymentdetails




#Yara Broker Credential
yara.broker.login.id=YaraBroker
yara.broker.password=Admin@01
