/*
 * Java domain class for entity "TrackingDetails" 
 * Created on 2021-10-09 ( Date ISO 2021-10-09 - Time 15:04:43 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.master.req;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;



/**
 * Domain class for entity "TrackingDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TrackingDetailsGetAllReq {


    
	@JsonProperty("Trackingid")
    private String     trackingId   ;  
	@JsonProperty("RequestReferenceNo")
    private String     requestReferenceNo      ;
	@JsonProperty("QuoteNo")
    private String     quoteNo   ;
	@JsonProperty("PolicyNo")
    private String     policyNo     ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("InsuranceId")
    private String companyId ;
	@JsonProperty("BranchCode")
    private String branchCode   ;
	@JsonProperty("ProductId")
    private String productId   ;


	  
	  
}
