/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "AcExecutiveMaster" ( stored in table "ac_executive_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class AcExecutiveMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    acExecutiveId ;
    
    private String     branchCode ;
    
    private String     companyId ;
    
    private String     status ;
    
    private Date       effectiveDateEnd ;
    
    private String     bankCode ;
    
     
}
