package com.maan.eway.bean;

import java.io.Serializable;
import java.util.Date;

/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:19:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "AcExecutiveMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BlockingIpAddressId.class)
@Table(name="blocking_Ip_Address")


public class BlockingIpAddress implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="IP_ADDRESS", nullable=false)
    private String    ipAddress ;

    @Column(name="STATUS", nullable=false, length=2)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_DATE", nullable=false)
    private Date       startDate;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", nullable=false)
    private Date       endDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



