/*
 * Created on 2022-11-21 ( 15:19:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "CompanyCityMaster" ( stored in table "company_city_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class CompanyCityMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    cityId ;
    
    private Date       effectiveDateEnd ;
    
    private Date       effectiveDateStart ;
    
    private String     stateId ;
    
    private String     countryId ;
    
    private String     regionId ;
    
    private String     companyId ;
    
     
}
