/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:19:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:19:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "CompanyProrataMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CompanyProrataMasterId.class)
@Table(name="company_prorata_master")


public class CompanyProrataMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="INSURANCEID", nullable=false, length=10)
    private String     insuranceid ;

    @Id
    @Column(name="PRODUCTID", nullable=false)
    private Integer    productid ;

    @Id
    @Column(name="SNO", nullable=false)
    private Integer    sno ;
    
    @Id
	@Column(name = "POLICY_TYPE_ID", nullable = false)
	private Integer policyTypeId;

    //--- ENTITY DATA FIELDS 
    @Column(name="STARTFROM")
    private BigDecimal startfrom ;

    @Column(name="ENDTO")
    private BigDecimal endto ;

    @Column(name="PERCENT")
    private BigDecimal percent ;

    @Column(name="STATUS", length=5)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date       effectiveDateStart ;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END")
    private Date       effectiveDateEnd ;
    
    
    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;
    
    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;
   
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date updatedDate ;
    //--- ENTITY LINKS ( RELATIONSHIP )


}



