/*
 * Created on 2022-11-21 ( 15:19:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "CountryMaster" ( stored in table "country_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class ContentAndRiskId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
	private String requestReferenceNo;
	private Integer riskId;
	private String sectionId;
	private Integer itemId;	
	//private String quoteNo;
	  private String     serialNoDesc;
	  private Integer locationId;


    
     
}
