/*
 * Created on 2022-11-21 ( 15:20:01 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "EserviceAllRisks" ( stored in table "eservice_all_risks" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class EserviceAllRisksId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     requestReferenceNo ;
    
    private Integer    sectionId ;
    
    private Integer    locationId ;
    
    private Integer    customerId ;
    
    private String     companyId ;
    
    private String     branchCode ;
    
    private Integer    itemId ;
    
     
}
