/*
 * Created on 2024-01-31 ( 16:10:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "EwayMotorMakemodelMaster" ( stored in table "eway_motor_makemodel_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class EwayMotorMakemodelMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    makeId ;
    
    private Integer    modelId ;
    
    private Integer    bodyId ;
    
    private String     companyId ;
    
    private String     branchCode ;
    
    private Integer    amendId ;
    
     
}
