/*
 * Created on 2024-02-01 ( 11:55:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "EwayVehicleMakemodelMasterDetail" ( stored in table "eway_vehicle_makemodel_master_detail" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class EwayVehicleMakemodelMasterDetailId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     vehicleid ;
    
    private Integer    productId ;
    
    private String     companyId ;
    
    private Integer    sectionId ;
    
    private Integer    makeId ;
    
    private Integer    modelgroupId ;
    
    private Integer    amendId ;
    
    private Integer    bodyId ;
    
     
}
