/*
 * Created on 2023-09-20 ( 16:47:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "MsLifeDetails" ( stored in table "ms_life_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MsLifeDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     requestReferenceNo ;
    
    private String     branchCode ;
    
    private String     companyId ;
    
    private String     endtCategoryId ;
    
    private Integer    endtTypeId ;
    
    private Double     exchangeRate ;
    
    private Integer    productId ;
    
    private Integer    riskId ;
    
    private Integer    sectionId ;
    
    private String     status ;
    
    private Long       vdRefno ;
    
     
}
