/*
 * Created on 2023-01-04 ( 13:04:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;
import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "PolicyDrcrDetail" ( stored in table "policy_drcr_detail" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class PolicyDrcrDetailId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     policyNo ;
    
    private String     quoteNo ;
    
    private BigDecimal chgId ;
    
    private String     companyId ;
    
    private String     productId ;
  
    private String     branchCode ;
    
     
}
