/*
 * Created on 2022-11-21 ( 15:20:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "ProductCoverOfsGridMaster" ( stored in table "product_cover_ofs_grid_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class ProductCoverOfsGridMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    ratingId ;
    
    private Integer    coverId ;
    
    private Integer    sectionId ;
    
    private Integer    productId ;
    
    private String     companyId ;
    
    private Integer    schemeId ;
    
     
}
