/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import jakarta.persistence.Column;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "AcExecutiveMaster" ( stored in table "ac_executive_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class RenewVehicleDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    @Column(name="VEHICLE_ID", nullable=false)   //--- ENTITY PRIMARY KEY 
   	private String    vehicleId ;
   	
   	@Column(name="OLD_REQUEST_REFERENCE_NO", nullable=false)
   	private String     OldrequestReferenceNo ;
   
 
}
