/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:19:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "AcExecutiveMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TermsAndConditionId.class)
@Table(name="terms_and_condition")


public class TermsAndCondition implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="SNO", nullable=false)
    private Integer    sno;

    @Id
    @Column(name="QUOTE_NO", nullable=false, length=100)
    private String     quoteNo;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=20)
    private String     branchCode;

    @Id
    @Column(name="PRODUCT_ID", nullable=false, length=20)
    private String    productId ;
    
    @Id
    @Column(name="LOCATION_ID", nullable=false, length=20)
    private String    locationId ;

    @Id
    @Column(name="SECTION_ID", nullable=false, length=20)
    private String     sectionId;
    
    @Id
    @Column(name="COVER_ID", nullable=false)
    private String    coverId;
    
    @Id
    @Column(name="ID", nullable=false)
    private Integer   id;

    @Id
    @Column(name="SUB_ID", nullable=false)
    private Integer  subId;
    
    @Id
    @Column(name="RISK_ID", nullable=false)
    private String  riskId;
    
        
    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=100)
    private String     requestReferenceNo;

    
    @Column(name="ID_DESC", length=100)
    private String     idDesc;
    
    @Column(name="SUB_ID_DESC", length=500)
    private String     subIdDesc;
    
    
    @Column(name="COMPANY_NAME", length=100)
    private String     companyName;
    
    @Column(name="BRANCH_NAME", length=100)
    private String     branchName;
    
    @Column(name="PRODUCT_NAME", length=100)
    private String    productName;
    
    @Column(name="SECTION_NAME", length=100)
    private String    sectionName;
    
    @Column(name="STATUS",length=1)
    private String     status ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="REMARKS",length=100)
    private String     remarks;

    @Column(name="CREATED_BY",length=100)
    private String  createdBy;

    @Column(name="UPDATED_BY",length=100)
    private String  updatedBy;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date  updatedDate ;


    @Column(name="AMEND_ID", nullable=false)
    private Integer  amendId;

    @Column(name="DOC_REF_NO",length=100)
    private String  docRefNo;
    
    @Column(name="Type_Id",length=1) 	
    private String  typeId;
    
    @Column(name = "EXCESS_PERCENTAGE")
    private Integer excessPercentage;
    
    @Column(name = "EXCESS_AMOUNT")
    private Double excessAmount;
    
    @Column(name = "CURRENCY")
    private String currency;
    
}



