/*
 * Created on 2022-11-21 ( 15:20:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "StateMaster" ( stored in table "state_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class TermsAndConditionId implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer    sno;
    private String     quoteNo;
    private String     companyId ;
    private String     branchCode;
    private String    productId ;
    private String     sectionId;
    private Integer   id;
    private Integer  subId;
    private String  riskId;
    private String     requestReferenceNo;
    private String    coverId;
    private String    locationId ;

     
}
