/*
 * Created on 2022-03-05 ( 12:12:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "TrackingDetails" ( stored in table "TRACKING_DETAILS" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class TrackingDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;
    private String     trackingId ;
    private String     companyId ;
    private String     riskId ;     
    private String     branchCode ;
    
     
}
