/*
 * Java domain class for entity "RawContentsDetails" 
 * Created on 2022-09-06 ( Date ISO 2022-09-06 - Time 11:31:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.req;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "RawContentsDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class EserviceContentsItemListReq implements Serializable {

    private static final long serialVersionUID = 1L;

	@JsonProperty("ItemId")
    private String     itemId    ;
	
	@JsonProperty("ItemDesc")
    private String     itemDesc    ;

	@JsonProperty("ItemName")
    private String     itemName     ;
	
	@JsonProperty("ItemValue")
    private String     itemValue    ;
  

      
	  
	  
}
