/*
 * Java domain class for entity "RawContentsDetails" 
 * Created on 2022-09-06 ( Date ISO 2022-09-06 - Time 11:31:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.req;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "RawContentsDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class EserviceContentsDetailsSaveReq implements Serializable {

    private static final long serialVersionUID = 1L;


	@JsonProperty("CustomerRequestReferenceNo")
    private String     requestReferenceNo ;
	
	@JsonProperty("SectionId")
    private String    sectionId    ;
	
	@JsonProperty("LocationId")
    private String    locationId       ;
	
	@JsonProperty("CustomerId")
    private String    customerId   ;
	
	@JsonProperty("InsuranceId")
    private String     companyId    ;
	
	@JsonProperty("BranchCode")
    private String     branchCode   ;
  
	@JsonProperty("ItemList")
    private List<EserviceContentsItemListReq>     itemList   ;
}
