/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-01-04 ( Date ISO 2023-01-04 - Time 13:04:14 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.service;
import java.util.List;

import com.maan.eway.bean.PolicyDrcrDetail;
import com.maan.eway.res.calc.DebitAndCredit;
/**
* <h2>PolicyDrcrDetailServiceimpl</h2>
*/
public interface PolicyDrcrDetailService  {

PolicyDrcrDetail create(PolicyDrcrDetail d);
PolicyDrcrDetail update(PolicyDrcrDetail d);
//PolicyDrcrDetail getOne(long id) ;
 List<PolicyDrcrDetail> getAll();
long getTotal();
//boolean delete(long id);
public boolean insertDRCR(List<DebitAndCredit> push,String quoteno );
}
